# Generated by Django 4.2.7 on 2023-12-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_profile',
            field=models.ImageField(blank=True, default=None, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
