# Generated by Django 4.2.7 on 2023-12-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_server_server_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(default='undefined', max_length=150),
        ),
    ]
